// 赛事预告
export const GET_TOURNAMENT_PREVIEW = 'GET_TOURNAMENT_PREVIEW';

export const UPDATE_TOURNAMENT_PREVIEW = 'UPDATE_TOURNAMENT_PREVIEW';

//复用接口
export const REUSE_UPDATE_TOURNAMENT_PREVIEW = 'REUSE_UPDATE_TOURNAMENT_PREVIEW';

// 当天赛事
export const GET_MATCH = 'GET_MATCH';

export const UPDATE_MATCH = 'UPDATE_MATCH';

// 当天赛事 用于过滤
export const GET_MATCH_FILTER = 'GET_MATCH_FILTER';

export const UPDATE_MATCH_FILTER = 'UPDATE_MATCH_FILTER';

// 指数走势2s
export const GET_EXPONENT_TREND = 'GET_EXPONENT_TREND';

export const UPDATE_EXPONENT_TREND = 'UPDATE_EXPONENT_TREND';

// 赛事详情
export const GET_MATCH_DETAILS = 'GET_MATCH_DETAILS';

export const UPDATE_MATCH_DETAILS = 'UPDATE_MATCH_DETAILS';

// PC赛事详情
export const GET_MATCH_INFO = 'GET_MATCH_INFO';

export const UPDATE_MATCH_INFO = 'UPDATE_MATCH_INFO';

// app实时统计
export const GET_APP_REALTIME = 'GET_APP_REALTIME';
export const UPDATE_APP_REALTIME = 'UPDATE_APP_REALTIME';

// 事件统计
export const GET_EVENT_STATISTICS = 'GET_EVENT_STATISTICS';
export const UPDATE_EVENT_STATISTICS = 'UPDATE_EVENT_STATISTICS';

// 根据赛事id查询直播信息
export const GET_LIVE_INFO_BY_ID = 'GET_LIVE_INFO_BY_ID';
export const UPDATE_LIVE_INFO_BY_ID = 'UPDATE_LIVE_INFO_BY_ID';

// 根据room id查询直播详情
export const GET_LIVE_DETAILS_BY_ROOM = 'GET_LIVE_DETAILS_BY_ROOM';
export const UPDATE_LIVE_DETAILS_BY_ROOM = 'UPDATE_LIVE_DETAILS_BY_ROOM';
