
// 登录
export const GET_LOGIN_EPIC = 'GET_LOGIN_EPIC';

export const UPDATE_LOGIN_REDUCER = 'UPDATE_LOGIN_REDUCER';

// 注册图形验证码
export const GET_RAND_CODE_EPIC = 'GET_RAND_CODE_EPIC';

export const UPDATE_RAND_CODE_REDUCER = 'UPDATE_RAND_CODE_REDUCER';

// 注册
export const GET_REGISTER_EPIC = 'GET_REGISTER_EPIC';


// 找回/绑定手机验证码验证码
export const GET_CODE_EPIC = 'GET_CODE_EPIC';
export const UPDATE_CODE_REDUCER = 'UPDATE_CODE_REDUCER';
// 绑定手机号
export const GET_BINDPHONE_EPIC = 'GET_BINDPHONE_EPIC'
export const UPDATE_BINDPHONE_REDUCER= 'UPDATE_BINDPHONE_REDUCER'
// 查询聊天室用户信息接口
export const GET_CHAT_USER_INFO = 'GET_CHAT_USER_INFO';
// 获取用户信息
export const GET_USER_INFO = 'GET_USER_INFO'; // 获取用户信息
export const UPDATE_USER_INFO_REDUCER = 'UPDATE_USER_INFO_REDUCER';

export const GET_USER_CARE_LIST = 'GET_USER_CARE_LIST'; // 获取用户关注列表
export const UPDATE_USER_CARE_LIST_REDUCER = 'UPDATE_USER_CARE_LIST_REDUCER';
// 导航栏关注列表2
export const GET_USERCARE_LIST = 'GET_USERCARE_LIST';
export const UPDATE_USERCARE_LIST_REDUCER = 'UPDATE_USERCARE_LIST_REDUCER';

// 退出登入接口
export const GET_LoginOut = 'GET_LoginOut';
export const UPDATE_LoginOut_REDUCER = 'UPDATE_LoginOut_REDUCER';

// 修改昵称
export const GET_Nickname_Epic = 'GET_Nickname_Epic';
export const UPDATE_Nickname_REDUCER = 'UPDATE_Nickname_REDUCER';

// 取消关注
export const GET_ATTENTIONSAID_EPIC = 'GET_ATTENTIONSAID_epic';
export const UPDATE_ATTENTIONSAID_REDUCER = 'UPDATE_ATTENTIONSAID_REDUCER';

// 充值客服列表
export const GET_CUSTOMERSERVICE_EPIC = 'GET_CUSTOMERSERVICE_EPIC'
export const UPDATE_CUSTOMERSERVICE_REDUCER = 'UPDATE_CUSTOMERSERVICE_REDUCER'

// 获取订阅赛事列表6条
export const GET_SUBSCRIBE = 'GET_SUBSCRIBE'
export const UPDATE_SUBSCRIBE = 'UPDATE_SUBSCRIBE'

// 金币充值记录 列表
export const GET_QUERYUGOLDRECHARGE_EPIC = 'GET_QUERYUGOLDRECHARGE_EPIC'
export const UPDATE_QUERYUGOLDRECHARGE_REDUCER= 'UPDATE_QUERYUGOLDRECHARGE_REDUCER'

// 支出记录
export const GET_EXPENDITURERECORD_EPIC = 'GET_EXPENDITURERECORD_EPIC'
export const UPDATE_EXPENDITURERECORD_REDUCER= 'UPDATE_EXPENDITURERECORD_REDUCER'

// 房管查询列表
export const GET_ROOMMANAGE_EPIC = 'GET_ROOMMANAGE_EPIC'
export const UPDATE_ROOMMANAGE_REDUCER= 'UPDATE_ROOMMANAGE_REDUCER'

// 房管撤销
export const GET_ROOMMANAGErevoke_EPIC = 'GET_ROOMMANAGErevoke_EPIC'
export const UPDATE_ROOMMANAGErevoke_REDUCER= 'UPDATE_ROOMMANAGErevoke_REDUCER'
// 房管添加
export const GET_ROOMMANAGEadd_EPIC = 'GET_ROOMMANAGEadd_EPIC'
export const UPDATE_ROOMMANAGEadd_REDUCER= 'UPDATE_ROOMMANAGEadd_REDUCER'
// 禁言用户列表
export const GET_GETUSERSHUTUPTIME_EPIC = 'GET_GETUSERSHUTUPTIME_EPIC'
export const UPDATE_GETUSERSHUTUPTIME_REDUCER= 'UPDATE_GETUSERSHUTUPTIME_REDUCER'
// 主播解除禁言
export const GET_UNMUTEFORBIDTALK_EPIC = 'GET_UNMUTEFORBIDTALK_EPIC'
export const UPDATE_UNMUTEFORBIDTALK_REDUCER= 'UPDATE_UNMUTEFORBIDTALK_REDUCER'
// 新增禁言
export const GET_SHUTUPFORBIDSENDMSG_EPIC = 'GET_SHUTUPFORBIDSENDMSG_EPIC'
export const UPDATE_SHUTUPFORBIDSENDMSG_REDUCER= 'UPDATE_SHUTUPFORBIDSENDMSG_REDUCER'
// 关联赛事
export const GET_ROOMSQUERYMATCHLISTINFO_EPIC = 'GET_ROOMSQUERYMATCHLISTINFO_EPIC'
export const UPDATE_ROOMSQUERYMATCHLISTINFO_REDUCER= 'UPDATE_ROOMSQUERYMATCHLISTINFO_REDUCER'
// 开播之前 设置房间信息
export const GET_LIVESETTING_EPIC = 'GET_LIVESETTING_EPIC'
export const UPDATE_LIVESETTING_REDUCER= 'UPDATE_LIVESETTING_REDUCER'
// 修改密码接口
export const GET_CHANGEPASSWORD_EPIC = 'GET_CHANGEPASSWORD_EPIC'
export const UPDATE_CHANGEPASSWORD_REDUCER= 'UPDATE_CHANGEPASSWORD_REDUCER'
// 获取推流地址
export const GET_STREAMSPUBLISHADDR_EPIC = 'GET_STREAMSPUBLISHADDR_EPIC'
export const UPDATE_STREAMSPUBLISHADDR_REDUCER= 'UPDATE_STREAMSPUBLISHADDR_REDUCER'
// 查询用户钱包
export const GET_USERQUERYWALLET_EPIC = 'GET_USERQUERYWALLET_EPIC'
export const UPDATE_USERQUERYWALLET_REDUCER= 'UPDATE_USERQUERYWALLET_REDUCER'
// 登录日志列表
export const GET_QUERYLOGINLOG_EPIC = 'GET_QUERYLOGINLOG_EPIC'
export const UPDATE_QUERYLOGINLOG_REDUCER= 'UPDATE_QUERYLOGINLOG_REDUCER'
// 用户打开基础设置
export const GET_OPENSNOTIFICATION_EPIC = 'GET_OPENSNOTIFICATION_EPIC'
export const UPDATE_OPENSNOTIFICATION_REDUCER= 'UPDATE_OPENSNOTIFICATION_REDUCER'
// 找回密码接口-身份验证
export const GET_CHECKIDENTITY_EPIC = 'GET_CHECKIDENTITY_EPIC'
export const UPDATE_CHECKIDENTITY_REDUCER = 'UPDATE_CHECKIDENTITY_REDUCER'
// 找回密码接口-重置密码
export const GET_RESETPASSWORD_EPIC = 'GET_RESETPASSWORD_EPIC'
export const UPDATE_RESETPASSWORD_REDUCER = 'UPDATE_RESETPASSWORD_REDUCER'
// 更新用户头像
export const UPDATE_USER_HEAD_IMAGE='UPDATE_USER_HEAD_IMAGE'